# Dataset
DATA_DIR = "/content/data/"
PRISTINE_FOLDER = ""
FORGERED_FOLDER = "rgb_imgs"
GROUND_TRUTH_FOLDER = "masks"
DATASET_NAME = "Spliced_COCO"
DATASET_SIZE = 500
IMG_SHAPE = (384, 256)
IMG_CHANNELS = 3

# Training
#TRAIN_PERCENT = 0.70
#VAL_PERCENT = 0.10
#TEST_PERCENT = 0.20
TRAIN_SIZE = 465
VAL_SIZE = 25
TEST_SIZE = 10
BATCH_SIZE = 6
EPOCHES = 150

# Learning
MOMENTUM = 0.9
WEIGHT_DECAY = 0.0005
LEARNING_RATE = 0.1

# Noise attack
NOISE_VARIANCE = 0.002
COMPRESSION_QUALITY = 100
